### ISSUE TITLE
Failed to create directory error when directory allredy exists.

### ISSUE THREAD

**Issue by Venomz3** [o10n-x/wordpress-javascript-optimization#12]
When clearing cache on o10n top menu and then accessing JavaScript optimization plugin I got those error messages:

Error during proxy update (shutdown callback): 
Failed to proxy https://static.xx.fbcdn.net/rsrc.php/v3ieFs4/yp/l/en_US/YfSazqs1aYt.js Error: Failed to create cache directory /wp-content/cache/o10n/js/proxy/f6/31/ad/
Failed to create directory /wp-content/cache/o10n/js/proxy/f6/31/ad/ Error: mkdir(): File exists

Failed to create cache directory /wp-content/cache/o10n/js/proxy/f6/31/ad/
Failed to create directory /wp-content/cache/o10n/js/proxy/f6/31/ad/ Error: mkdir(): File exists

The optimization cache has been cleared. 

Failed to create cache directory /wp-content/cache/o10n/js/src/34/db/c1/
Failed to create directory /wp-content/cache/o10n/js/src/34/db/c1/ Error: mkdir(): File exists

Failed to create cache directory /wp-content/cache/o10n/js/concat/b5/d8/39/
Failed to create directory /wp-content/cache/o10n/js/concat/b5/d8/39/ Error: mkdir(): File exists

Failed to create cache directory /wp-content/cache/o10n/css/proxy/12/5c/16/
Failed to create directory /wp-content/cache/o10n/css/proxy/12/5c/16/ Error: mkdir(): File exists
 
Is this known issue or new one ?

**Comment by optimalisatie** [comment]
Hi Jari,

Thanks a lot for the feedback!

It appears that when you emptied the cache that there were multiple processes trying to create a directory. 

The script first checks if the directory exists and then tries to create the directory. 

```php
if (!is_dir($path)) {
    if (!@mkdir($path, $mode, $recursive)) {
        $error = error_get_last();
        throw new \Exception('Failed to create directory ' . $this->safe_path($path) . (($error) ? ' Error: ' . $error['message'] : ' Error: unknown'));
    }

    // set permissions
    @chmod($path, $mode);
}
```

It may be that the HDD was slowed due to the `delete` process which caused the simple `mkdir` command to slow to such extend (it may be a millisecond) that a second process was started to create the same directory, causing the plugin to throw an error that is displayed in the admin.

#### PHP Exceptions

A unique feature of the WPO plugins is that it uses PHP Exceptions that are logged to the WPO plugin admin so that you have a clear view if anything goes wrong. It also enables a website to remain usable if the WPO plugin (or parts of it) fail.

> ### [Why WP_Error Sucks](https://journal.rmccue.io/165/why-wp_error-sucks/)
> As anyone who has worked with WordPress knows, WordPress supported PHP 4 for a long time, even after many other projects had switched. The advantage of this was supporting significantly more hosts, with most PHP 5-only features either not being needed or being easy to reimplement.
> 
> One of the new features added to PHP in PHP 5 was exception handling... 

#### PHP errors in browser console

A unique innovation is that PHP errors are also displayed in the browser console when debug mode is enabled. Some of the Exceptions may not be fatal (e.g. a failed regular expression). With debug mode enabled you can find these errors in the browser console for optimization purposes.

![image](https://user-images.githubusercontent.com/8843669/41180460-a03ca1a4-6b6e-11e8-8cbb-599415311831.png)

We have detected a bug that prevents PHP errors to be displayed in the browser console. It will be fixed in the next update.

We also added a fail safe to the directory creation method so that it won't fail if multiple processes simultaneously try to create the same directory. It now uses `file_exists` instead of `is_dir` which is faster.

```php
/**
 * Create directory
 *
 * @param  string $path      Directory path to create.
 * @param  octal  $mode      The permission mode for the directory.
 * @param  bool   $recursive Create path recursively.
 * @return bool   Created true/false.
 */
final public function mkdir($path, $mode = false, $recursive = false)
{
    // set default mode
    if (!$mode) {
        $mode = O10N_CACHE_CHMOD_DIR;
    }

    // Restrict access to /wp-content/...
    if (!$this->valid_path($path)) {
        throw new \Exception('Failed to create directory ' . $this->safe_path($path) . ' (Invalid directory path)');
    }

    // check if directory exists
    if (!file_exists($path)) {
        if (!@mkdir($path, $mode, $recursive)) {

            // check if directory is already created by a concurent process, ignore error
            if (!file_exists($path)) {
                $error = error_get_last();
                throw new \Exception('Failed to create directory ' . $this->safe_path($path) . (($error) ? ' Error: ' . $error['message'] : ' Error: unknown'));
            }
        }

        // set permissions
        @chmod($path, $mode);
    } elseif (!is_dir($path) && file_exists($path)) {
        throw new \Exception('Failed to create directory ' . $this->safe_path($path) . ' Error: path exists as a file (not a directory)');
    }

    return true;
}
```

The update will be published soon.

**Comment by optimalisatie** [comment]
The issue has been fixed in the latest update.

https://github.com/o10n-x/wordpress-html-optimization/releases/tag/0.0.27
