### ISSUE TITLE
Possible bug or intended feature

### ISSUE THREAD

**Issue by Venomz3** [o10n-x/wordpress-javascript-optimization#13]
Procedure: Removing everything from Async config filter and also removing checkbox form async loading then press save then going back to enable Async loading then all JSON code is back there. So multiple settings changes are not applied.  

Proper way to remove code for JSON box seems to be: Empty code then click save.  

After that you can verify that box is and stays empty. Now it`s possible to disable Async loading and JSON box stays empty.  

Also If you want to disable <link rel="preload" as="script"> or enable config filter those settings are not remembered when you set them same time when you enable or disable Async loading. 
 Even they are like child settings to Async loading.  

This is confusing behavior.  Intended behavior or bug  ?

**Comment by optimalisatie** [comment]
Hi Venomz3,

Thank you for your feedback and our apologies for the late reply! The plugin has been updated in recent months. If you would still be interested to try the plugin and/or are still experiencing the issue, please let us know!

**Comment by Venomz3** [comment]
Hi  Optimalisatie,

Just checked that it works like that.  But when thinking now differently that is logical that when disabling async delivery then it does not saved items that are required be that setting.   



It might be confusing when somebody removes or edits some async filter code, removes setting async delivery and saves. When that somebody some other time enables async delivery then he realizes changes to filter are lost.  Maybe that`s extra code (without no real value ) when checking and notifying that JSON changes are lost when that person disables async delivery without saving JSON first.    

I know how to use it now as I`ve testing to report possible bugs. For somebody who has not used it before it might be confusing. 
Just give it a thought and close this thread.

**Comment by optimalisatie** [comment]
Thank you very much for the valuable feedback!

In regards to your comment, it is the intended functionality. The form input is validated against a JSON schema en thus when async loading is turned off, the JSON input is ignored so that it will not trigger an error. 

Validation of input is very robust. There is almost no PHP logic involved, it's pure JSON schema.

More information about JSON schema's is available on https://json-schema.org/

The JSON schema's of the plugins are available in the optimization plugin core:

https://github.com/o10n-x/wordpress-o10n-core/tree/master/schemas

The plugin is 100% JSON controlled. In essence, the WordPress admin panel isn't required to use the plugin. JSON schema provides a mechanism for both working with the (thousands of) settings (e.g. via external editors / by AI) and for enforcing validity. It is therefor a very reliable, efficient and future proof concept for managing thousands of optimization settings that may require fine tuning on per-page level or even on per device-level.

Our originally planned Advanced Optimization plugin contained a JSON profile loading innovation that was capable of conditionally loading millions of JSON optimization profiles with microsecond speed. It was designed for AI so that it could create a unique optimization document for each page if needed. When the plugin was quickly converted to the multi-plugin format, the JSON config storage was moved to WordPress options (database) but it would be possible to transition to the more efficient JSON profile loading system later. We recently added a sort of alternative via a [Stealth Optimization Config Proxy](https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55). The provided concept enables to edit the plugin settings using physical `.json` files that can be loaded conditionally via a stealth optimization plugin proxy. More information is in the release publication: https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55
