### ISSUE TITLE
Loading JS script depending on the screen width

### ISSUE THREAD

**Issue by ArekZw** [o10n-x/wordpress-javascript-optimization#22]
Is there a way to load the script only when the screen is larger/smaller than X px? (similar to media queries in CSS)?

**Comment by optimalisatie** [comment]
Hi @ArekZw,

Thank you for your question! 

Yes, a unique innovation provided by the plugin is responsive script loading. It enables to load scripts conditionally based on a Media Query. 

An example use case could be a complex desktop design that scales back to a simplistic design for mobile phones. It may be that +1mb worth of scripts would not be required for the mobile responsive design. The Javascript Optimization plugin makes it possible (for the first time) to load certain scripts (or a concatenated group of scripts) only for specific media queries, thus potentially gaining a lot of speed for a responsive mobile design.

Javascript data is not the same as for example CSS or image data. It has a much bigger impact. Even the ability to save just 100kb of scripts on a mobile device could have a profound effect on the performance. Responsive script loading could therefor be of high value.

![1_prvznizf9jq_qadf5lqhpa](https://user-images.githubusercontent.com/8843669/49022296-cbb6aa80-f194-11e8-8c0d-1d3aafee4b75.png)

More information is available in the following article by Google:

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization/

The script loader provided by the plugin provides an additional innovation named _timed execution_. While normally a script would always be executed after it is downloaded, the script loader provided by the Javascript Optimization plugin makes it possible to download the scripts early and execute the scripts later, conditionally using a media query or using a timing mechanism such as `requestIdleTime` or `requestAnimationFrame` which is verry effective for device based javascript performance optimization.

You can both conditionally load (download) scripts and/or execute scripts.

For example, to download scripts conditionally using a Media Query by default, you could use the following configuration:

![image](https://user-images.githubusercontent.com/8843669/49022635-99f21380-f195-11e8-8699-d385b7025f6a.png)

It would make more sense however to use the Asycn Config filter to apply conditional loading to individual scripts or concat groups. 

![image](https://user-images.githubusercontent.com/8843669/49022902-47652700-f196-11e8-88bd-e6dde947f84d.png)

```json
[
  {
    "match": "/b\\.js/",
    "regex": true,
    "async": true,
    "exec_timing": {
      "type": "requestIdleCallback",
      "timeout": 1000,
      "setTimeout": 100
    }
  }
]
```

A concat group is a group of scripts merged to a single script for more efficient loading.

Another unique innovation provided by the plugin is that you can time the execution of individual scripts within the concat group. For example, a group containing `a.js`, `b.js` and `c.js` could time the execution of `b.js` using `requestIdleCallback`. This again is of high value for more advanced optimization and enables to achieve Google Lighthouse 100-scores for javascript heavy websites.

Regrettably, the project is on hold due to a ban from WordPress.org. Therefor we never got to the point of creating documentation and tutorials.

There is a parntership/takeover offer available. We are now waiting for a new driving force to take over the project, or it will remain as it is and it would demand more from users to learn how to use it.

https://github.com/o10n-x/wordpress-css-optimization/issues/34

**Comment by ArekZw** [comment]
Thank you for the thorough explanation, I will try to implement this functionality in my app.

I know how you were treated by Wordpress.org, I'm very sorry because your tool is great. I hope it will be further developed.
