### ISSUE TITLE
Feature request: gzip concatenated file

### ISSUE THREAD

**Issue by Ost11** [o10n-x/wordpress-javascript-optimization#23]
What about pre-gzip concatenate file (with maximum ratio - 9)? Could it speed up delivery with gunzip enabled in nginx, for example? If yes such option may be enabled with css concatenated delivery.

**Comment by optimalisatie** [comment]
Hi @Ost11,

Thank you very much for the feature request!

Yes, static-gzip can help reduce the server load by saving the CPU-time required for on the fly gzip-compression. It may be that Nginx optimizes the on-the-fly gzip compression in newer server versions so that the standard gzip compression option is already pretty performant for most websites, however, when a website receives a great amount of traffic that hits the limit of the server capacity, static gzip is simply an optimization to apply for best performance.

We have recently added static-gzip to our latest CSS optimization solution [📐 Style.Tools](https://github.com/style-tools). The Style.Tools solution will soon be enhanced with concatenation, async CSS loading (next level), async injected stylesheet capture (to remove, optimize or modify code of stylesheets that could otherwise be out of control) and more. It contains a cutting edge critical CSS generator based on PostCSS for better results than the leading tools Penthouse.js and Critical. There is a WordPress plugin available. 

The WordPress Javascript Optimization plugin project is current on hold awaiting a new driving force to take over the project. After the ban on WordPress.org (for an unknown motive), the future of the project became uncertain. 

**Takeover / partnership offer: Advanced Google Lighthouse optimization plugin**
https://github.com/o10n-x/wordpress-css-optimization/issues/34

The quality of the javascript optimization plugin is very good. It contains many innovations that enable to achieve stable Google Lighthouse 100-scores for javascript heavy websites, e.g. WooCommerce. It is of high value. On a webshop from one of our customers it has trippled the traffic in just 3 months. It adds to the revenue and for SEO it is of high value. It can provide 'the absolute best performance' for a WordPress website.

If you happen to know a party who would be interested to take over the project, so that it can be further developed, please let us know. Static gzip will then be a feature that can be added.
