### ISSUE TITLE
rel_preload => true breaks dependence

### ISSUE THREAD

**Issue by ArekZw** [o10n-x/wordpress-javascript-optimization#25]
When I set "rel_preload" on jquery to true, scripts that depend on jQuery are loaded before jQuery.

Is it possible for dependencies to wait for jquery which has rel_preload set to true?

```
 'js.async.filter.config' => 
  array (
    0 => 
    array (
      'match' => 'jquery.min.js',
      'async' => true,
      **'rel_preload' => true,**
    ),
    1 => 
    array (
      'match' => 'wpmm.js',
      'async' => true,
      **'dependency' => 'jquery',**
    ),
),
```

**Comment by optimalisatie** [comment]
There should be no difference with `rel_preload`. 

The PHP plugin will simply insert `<link rel="preload" as="script">` in the header that will initiate a download and the script loader will then process the scripts as it normally would (using the stable [little-loader](https://github.com/walmartlabs/little-loader) by Walmart Labs to execute a script, as if it is normally loaded). So it simply serves to speed up the initial download.

There is just 1 difference in the script loader when using `localStorage` to cache scripts. Instead of inserting the script at the position before the `<script data-o10n>` element using `insertBefore`, it will replace the `<link rel="preload" as="script">` element with the script element containing the cached script text.

**Comment by ArekZw** [comment]
I can not reproduce this bug. Either it only occurs in specific situations or I changed something at localStorage. If the problem appears again and will not depend on LocalStorage, I'll let you know.
