### ISSUE TITLE
js.minify.enabled: true breaks dependences in js.async.filter.config

### ISSUE THREAD

**Issue by ArekZw** [o10n-x/wordpress-javascript-optimization#26]
js.minify.enabled: true breaks dependences in js.async.filter.config

config:
```
{
  "js": {
    "async": {
      "enabled": true,
      "filter": {
        "enabled": true,
        "type": "include",
        "config": [
          {
            "match": "jquery.min.js",
            "async": true
          },
          {
            "match": "wpmm.js",
            "async": true,
            "dependency": "jquery.min.js"
          }
        ]
      }
    },
    "minify": {
      "enabled": true
    }
  }
}
```
![deps](https://user-images.githubusercontent.com/11788346/49815162-70c3ac80-fd6b-11e8-8e2c-ce5bdf1651c9.png)

When I change js.minify.enabled to false, all works fine

**Comment by optimalisatie** [comment]
Hi @ArekZw,

Thank you for the feedback!

Dependency matching is javascript based and (for compression purposes) currently only matches based on the script URL (it uses a compression mechanism so that only the smallest part of the script hash is included in the config JSON). It means that when a script is minified, it won't be matched against it's original file name.

The dependency loader should be enhanced to selectively include the original file name for minified stylesheets, and only when it is being matched for (to prevent data from 10-20+ scripts in the header). It would require a more advanced enhancement. It would be a very specific use case and I am not certain that many users would use the same configuration.

Normally, a user will most likely use the concatenate feature and it would then be possible to match dependencies based on the group name. For example, if you would create a concat group named `jquery`, you could match it as dependency. It could be a quick fix solution in your case since in practice, it will provide the exact same result (jQuery minified and selectable as dependency in other scripts).

**Comment by ArekZw** [comment]
thanks for the answer

>  It would be a very specific use case and I am not certain that many users would use the same configuration.
It seems to me that asynchronous script loading and minification are what draws attention to this plugin.

Indeed, fortunately, concatenate scripts solves part of my problems, but generate next... concatenate breaks load_timing and exec_timing from js.async.filter.config. Is there any way to set load_timing and exec_timing to concatenate groups?

I need it because I intensely use 2lvl (jquery -> script -> script) dependencies with inview load/exec time. Currently, I have to choose between dependencies (js.async.filter.config) and minification (concatenate).

Simplistically (deps: jQuery -> Script1 -> Script2):
jQuery - use concate (all okay)
Script1 - when I use concate, inview load/exec time breaks, if I use js.async.filter.config - minification doesn't work (here is problem)
Script2 - use js.async.filter.config (all okay)

I know that this dependency case is quite specific, but I am reporting it to show that there are other reasons why js.async.filter.config should allow for minification and dependencies at the same time.

I realize that it is difficult to control such a number of combinations of settings and I appreciate your work very much.
