### ISSUE TITLE
JShrink: PHP Fatal error: ob_start(): Cannot use output buffering in output buffering display handlers

### ISSUE THREAD

**Issue by ArekZw** [o10n-x/wordpress-javascript-optimization#27]
When I try to use JShrink js minifier I get error in logs:
JShrink: PHP Fatal error: ob_start(): Cannot use output buffering in output buffering display handlers

Problem is in my PHP configuration or incompatibilities between your plugin and jshrink? (using buffer in buffer)

**Comment by optimalisatie** [comment]
Hi @ArekZw,

Thank you for testing the experimental Javascript minifier [JShrink](https://github.com/tedious/JShrink) based on code / JSON schema research. JShrink isn't officially included in the plugin and thereby not selectable from the WordPress admin.

We initially intended to include JShrink as a minifier that could provide the plugin with a unique edge over existing plugins such as Autoptimize, but indeed for the mentioned error, the library didn't support the use within a `ob_start` output buffer.

We've requested the authors to consider to change the design of the library. Regrettably, there was no reply.

https://github.com/tedious/JShrink/issues/73

Since the plugin also provides [Google Closure Compiler](https://github.com/google/closure-compiler) via a free API, which not only compresses Javascript but also optimizes it for speed, it was decided to abandon JShrink. The initial integration is still available in the plugin and thus configurable via JSON, however, the error would need to be resolved in the JShrink library.

Regrettably, the free API provided by Google has not proven to be 100% reliable and it is also limited.

A unique innovation provided by the plugin is that you can use any Javascript minifier/optimizer via a WordPress filter. It would for example be possible to use a local Node.js server with [UglifyJS](https://github.com/mishoo/UglifyJS) or Closure Compiler. This could be performant (low latency) and provide a much better result than a PHP based solution.

### Google Cloud Function Javascript Minifier

An example: It is possible to use a [Google Cloud Function](https://cloud.google.com/functions/) via Nginx. It is very simple to setup and it would support (in theory) unlimited javascript minification requests per second without performance degradation. 

If you provide freelance optimization services, a Cloud Function (on the billing account of a customer) could be a quick to setup solution for the most perfect optimization result (professional Node.js optimization software) while reliably supporting unlimited traffic. The customer would just need to spend a small amount on Google Cloud costs per month. The costs could be low since you just pay for what you use. Google also offers a free tier per month. Minified javascript could remain valid for months. 

https://cloud.google.com/functions/

To setup a Google Cloud Function based Javascript minifier for WordPress that supports unlimited traffic and professional optimization software, you could use the following simple Nginx boilerplate and design a custom Google Cloud Function that will accept a parameter `js` with the code to minify and that then returns the minified code to the caller (a PHP WordPress filter).

### Nginx Google Cloud Function API endpoint

```nginx
# google cloud optimization function
upstream o10n-function {
    server us-central1-yourapp-199412.cloudfunctions.net:443;
}

# your webserver
server {
    listen 443 ssl http2;
    # ...

    # optimization function
    location /o10n-js-minify/ {
        allow 127.0.0.1; # allow only WordPress to make a call
        deny all;

        proxy_pass https://o10n-function/o10n-javascript;

        proxy_set_header X-Real-IP $the_real_ip;
        proxy_set_header X-Forwarded-For $the_real_ip;
        proxy_set_header Host us-central1-yourapp-199412.cloudfunctions.net;
        proxy_http_version 1.1;
    }
}
```

### WordPress Google Cloud Function javascript minifier filter

```php
/* Google Cloud Function Javascript minifier */
add_filter('o10n_js_custom_minify', function ($JS) {

    // post javascript to Google Cloud Function for minification
    $minified = wp_remote_post('/o10n-js-minify', array(
		'method' => 'POST',
		'timeout' => 60,
		'httpversion' => '1.1',
		'blocking' => true,
		'headers' => array(),
		'body' => array( 'js' => $JS )
    ));

    /**
     * @todo add error handling
     * @see https://codex.wordpress.org/Function_Reference/wp_remote_post
     */

    return $minified;
});
```

It is a quick concept, written quickly in this Github message. It should work but it could be optimized to achieve better performance, to prevent blocking a page load in diverse situations (e.g. temporary network failure, Google Cloud Functions technical/billing issues etc).

If you service many customers, you could create a central dedicated API endpoint and work with security credentials (example) and charge customers a monthly fee for access. It would make it more easy to maintain and could save costs.

**Comment by ArekZw** [comment]
Thank you for the extensive explanation. I just often reach the limit of Google Closure API calls. Thanks for the suggestion to run your own Closure service. I will probably go this way.
