### ISSUE TITLE
Javascript cache is getting huge

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-javascript-optimization#7]
Hi! 

I just noticed that the o10n javascript cache reached 2-4 GB. Any idea how to prevent this?

**Comment by optimalisatie** [comment]
Hi AlphaDE,

Thanks a lot for providing feedback!

In regards to the cache size, it is the same as with most other automated Javascript minification plugins (such as Autoptimize). When a minified or concatenated script contains a changing or random string the minified hash will change on each request causing the cache to fill up. The issue is more likely to occur when inline scripts are included in the concatenation. For example, a Google Tag Manager snippet containing a product ID would create a new cache file for each product ID.

The Javascript Optimization plugin contains a automated cache cleanup system that removes expired and unused cache entries (it keeps track of cache that is used for optimal efficiency and index hash preservation). However, if the website receives quite some traffic the cache may build up quickly (each request may create several new cache files).

To resolve the issue it is required to discover which script is causing the cache hash to change on each request. An option is to open two pages and copy the minified javascript code into an online diff tool:

https://www.google.nl/search?q=online+text+diff

It will show what part of the javascript is different. It would then be possible to exclude the specific script or apply a custom optimization.

When configured correctly, the javascript cache size should remain at a steady level.

**Comment by optimalisatie** [comment]
Hi AlphaDE,

If you emptied the gigabytes of javascript cache while a page cache layer (e.g. CloudFlare or a server side cache) was still pointing to the old cache file locations that may have caused a disparity. This also occurs with any other minifier solution such as Autoptimize. 

To make sure that the cached files are accessible for Google you could use the "Fetch as Google" function from Google Webmaster Tools. You can use it to spider a javascript file as well:

![image](https://user-images.githubusercontent.com/8843669/39148751-6d7b597c-473d-11e8-834a-3e6c8f96eebf.png)

https://www.google.com/webmasters/tools/googlebot-fetch-details?hl=de

Did the cache size stabilize after the removal of the dynamically changing script?

**Comment by optimalisatie** [comment]
If you are still having issues, please let us know!

**Comment by AlphaDE** [comment]
Later... after comparing the Autooptimize setup with the JS Optimization setup, I assume that this was the main reason:
"Extract inline <script> elements and include the javascript in the concatenated script."

Autooptimize has a warning there, that this might cause increasing cache sizes. I did not enable it this time and cache sizes are yet stable.

**Comment by AlphaDE** [comment]
Is there any way to implement a special handling for AMP? After reverting back to your plugin suite, I got tonight

The required tag "amphtml engine v0.js script" is missing or wrong 
Illegal attribute in HTML tag "link rel=preload"

**Comment by optimalisatie** [comment]
It may be best to disable the optimization plugins for AMP unless you know what you are doing. 

Our originally planned Advanced Optimization plugin would allow for environment based optimization, which would make it possible to create a custom optimization specifically for AMP or even "iPhone 5 on AMP". 

With the current plugin you could conditionally modify options using a WordPress filter, but that would require custom PHP based logic.

**Comment by AlphaDE** [comment]
Jan,

thx for the quick reply.

How do I disable it specifically for AMP? AMP is directly supported by 
the theme...

Regards,

Andreas

Am 07.05.2018 08:11, schrieb Jan Jaap:

**Comment by optimalisatie** [comment]
You can disable the optimization by setting `define('O10N_DISABLED', true);` or using a WordPress filter:

```php
add_filter('o10n_disabled', function() { 
	
	# disable optimization for AMP pages
	if (function_exists('is_amp_endpoint') && is_amp_endpoint()) { return true; } 

	return false;
});
```

**Comment by AlphaDE** [comment]
Thx,

where to put that, do I need a child theme for that?

Wouldn't it be useful to be able to configure that within your plugin suite?

**Comment by AlphaDE** [comment]
Without including the inline scripts, the cache sizes remain reasonable.

Nevertheless, Google Webmaster Console is reporting again spiking 404 on

wp-content/cache/o10n/js/concat/...

Any idea?
