### ISSUE TITLE
Spiking numbers of 404 not found on 	 wp-content/cache/o10n/js/

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-javascript-optimization#8]
Hey John,

despite that my JS cache is stable at 21 MB, Google Webmaster tools are reporting spiking (>1k) numbers of 404 not found errors, all on  wp-content/cache/o10n/js/ items.

Any idea how to fix that?

Regards,

Andreas

**Comment by optimalisatie** [comment]
Hi Andreas,

Thank you very much for the extensive feedback!

In regards to the issue. The cause is most likely related to a javascript file with a changing URL which causes the concatenated hash to change on each request which in turn causes a disparity between a page cache and the concatenated hash cache.

To make the hash reliable and persistent for each page it will be required to sanitize changing URLs using the URL filter.

First, to detect scripts with a changing URL you can use the `define('O10N_DEBUG', true);` option in wp-config.php.

It will print the contents of the concatenated file in the console.

![image](https://user-images.githubusercontent.com/8843669/39864671-a45923ba-544a-11e8-83ba-2628744fc631.png)

To rewrite a dynamic URL into a static URL you can use the URL filter. For example, the following config would replace `../script.js?t=123456789` into `../script.js`.

```json
[
  {
    "url": "/script\\.js\\?t=([0-9]+)$/i",
    "regex": true,
    "replace": "/wp-content/plugins/plugin_name/public/script.js"
  }
]
```

![image](https://user-images.githubusercontent.com/8843669/39864536-337193da-544a-11e8-92c3-f3952a6a9d24.png)

**Comment by AlphaDE** [comment]
I tried to analyze this. 

The only place where I found such a parameter was in a .css

https://static.mydomain.de/wp-content/plugins/wp-filebase/wp-filebase.css?t=1461036590"

where I tried to replace this with

[{"url":"/wp-content/plugins/wp-filebase\\.css\\?t=([0-9]+)$/i","regex":true,"replace":"/wp-content/plugins/wp-filebase/wp-filebase.css"}]

in the URL filter of the CSS optimization plugin. Nevertheless, I see no change in the debug output.

As said, in the .js concat, I cannot see anything.

0: "https://static.mydomain.de/wp-includes/js/jquery/jquery.js"
​​1: "https://static.mydomain.de/wp-includes/js/jquery/jquery-migrate.min.js"
​​2: "https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js"
​​3: "https://static.mydomain.de/wp-content/plugins/pie-register/js/prVariablesDeclaration.js"
​​4: "https://static.mydomain.de/wp-content/plugins/pie-register/js/datepicker.js"
​​5: "https://static.mydomain.de/wp-content/plugins/pie-register/js/jquery.alphanum.js"
​​6: "https://static.mydomain.de/wp-content/plugins/pie-register/js/piereg_validation.js"
​​7: "https://static.mydomain.de/wp-includes/js/zxcvbn-async.min.js"
​​8: "https://static.mydomain.de/wp-content/themes/graphene-plus/bootstrap/js/bootstrap.min.js"
​​9: "https://static.mydomain.de/wp-content/themes/graphene-plus/js/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"
​​10: "https://static.mydomain.de/wp-content/themes/graphene-plus/js/bootstrap-submenu/bootstrap-submenu.min.js"
​​11: "https://static.mydomain.de/wp-content/themes/graphene-plus/js/html5shiv/html5shiv.min.js"
​​12: "https://static.mydomain.de/wp-content/themes/graphene-plus/js/respond.js/respond.min.js"
​​13: "https://static.mydomain.de/wp-content/themes/graphene-plus/js/jquery.infinitescroll.min.js"
​​14: "https://static.mydomain.de/wp-includes/js/comment-reply.min.js"
​​15: "https://static.mydomain.de/wp-content/themes/graphene-plus/js/graphene.js"
​​16: "https://static.mydomain.de/wp-content/plugins/advanced-access-manager/media/js/aam-login.js"
​​17: "https://static.mydomain.de/wp-includes/js/jquery/ui/widget.min.js"
​​18: "https://static.mydomain.de/wp-includes/js/jquery/ui/tabs.min.js"
​​19: "https://static.mydomain.de/wp-content/plugins/pie-register/js/prVariablesDeclarationFooter.js"
​​20: "/wp-admin/js/password-strength-meter.min.js"
​​21: "https://static.mydomain.de/wp-content/plugins/pie-register/js/pie_password_checker.js"
​​22: "https://static.mydomain.de/wp-includes/js/imagesloaded.min.js"
​​23: "https://static.mydomain.de/wp-includes/js/masonry.min.js"
​​24: "https://static.mydomain.de/wp-includes/js/wp-embed.min.js"
​​25: "https://static.mydomain.de/wp-content/plugins/eu-cookie-law/js/scripts.js"

Despite that, I have still a huge number of errors on the Google console.

Any hints?

**Comment by AlphaDE** [comment]
Update... with no further changes since the last post, the errors at Google dropped to zero... let's see whether this stabilizes.

**Comment by AlphaDE** [comment]
There are no more errors yet on the Google console, so I close this issue. Great job!
