### ISSUE TITLE
Disable optimization on AMP

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-javascript-optimization#9]
You recently wrote

You can disable the optimization by setting define('O10N_DISABLED', true); or using a WordPress filter:

add_filter('o10n_disabled', function() { 
	
	# disable optimization for AMP pages
	if (function_exists('is_amp_endpoint') && is_amp_endpoint()) { return true; } 

	return false;
});

How to implement that without breaking the update functions of the theme? Can you include that into the optimization plugin suite and catch it there (make it configurable)?

Google reports all AMP pages broken and does not index them anymore.

**Comment by AlphaDE** [comment]
Jan, any updates on this... AMP pages are currently completely broken :(

**Comment by mxmkmarquette** [comment]
add_action( 'template_redirect', 'my_page_template_redirect' ); function my_page_template_redirect(){ if (is_amp_endpoint()) { define('O10N_DISABLED', true); } }

try this last time i was using amp it's what have been working for me.

**Comment by AlphaDE** [comment]
Where....

**Comment by mxmkmarquette** [comment]
Function.php is where it goes.

**Comment by AlphaDE** [comment]
See my first post... I would under all circumstances like to avoid to touch the theme or Wordpress itself as it leads with the many sites I host to a lot of trouble on updates.

The plugin knows the status by itself or could add that...

**Comment by mxmkmarquette** [comment]
dude it's one line of code, don't be lazy ass. lol or make a plugin like it will take 10 sec. of your time, and you upload this plugin to everysite and activate it and bang enjoy

**Comment by AlphaDE** [comment]
Again, why should I make a plugin or modify the core/theme and why isn't possible that the plugin does it itself? I assume I am not the only one... Autoptimize I used before did NOT break my AMP pages. 
I am not a plugin developer.
Conclusion: Javascript optimization plugin breaks AMP and the user should modify Wordpress core/themes or write another plugin to fix that. A little bit ridicoulus.

**Comment by mxmkmarquette** [comment]
like

```
<?php
/*
Plugin Name: Disabling Optimization on AMP
Plugin URI: your url
Description: the description.
Version: 0.01
Author: your name
Author URI: your url as author

// Desactivate optimization on AMP
add_action( 'template_redirect', 'my_page_template_redirect' ); function my_page_template_redirect(){ if (is_amp_endpoint()) { define('O10N_DISABLED', true); } }
?>
```

**Comment by mxmkmarquette** [comment]
i think if you use this plugin, that it's nowhere on wordpress.org, that people either find it by doing search on github will probably figure out a way to use it...

because like there a lot's of amp plugin and i'm sure it's easier that the guy using x or y version of amp, try some of the solution here to fix the problem...

**Comment by AlphaDE** [comment]
It does not seem to work... /amp/ pages are still delivered as o10n optimized version.

**Comment by mxmkmarquette** [comment]
witch plugin are you using for your amp thingy?

**Comment by AlphaDE** [comment]
No plugin, it's natively supported by Graphene Plus theme.

o10n DEBUG shows a processing of

concat: (6) […]
​​
0: "https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"
​​1: "https://cdn.ampproject.org/v0/amp-iframe-0.1.js"
​​2: "https://cdn.ampproject.org/v0/amp-social-share-0.1.js"
​​3: "https://cdn.ampproject.org/v0/amp-ad-0.1.js"
​​4: "https://cdn.ampproject.org/v0/amp-sticky-ad-1.0.js"
​​5: "https://cdn.ampproject.org/v0.js"

and I assume that Google does not like that:

The required tag "amphtml engine v0.js script" is missing or wrong.

**Comment by AlphaDE** [comment]
It includes V 0.6.2 of the Wordpress AMP implementation

**Comment by optimalisatie** [comment]
We will have a look into it.

It is correct however that the WPO optimization plugins are different from most other WordPress plugins such as Autoptimize. 

The WPO plugins intend to be __purely focused on optimization technologies__ instead of modifying / controlling WordPress. This enables to control the optimization using JSON that is portable to any website and platform.

An example: recently a user requested to remove WordPress Emoij javascript. It is a _script injected script_ that is impossible to remove with a PHP based (HTML) filter.

Other plugins offer an option to delete the complete emoji functionality from WordPress, e.g. Autoptimize uses the following code:

```php
// disable emoji's functions
function autoptimize_extra_disable_emojis() {
    // all actions related to emojis
    remove_action( 'admin_print_styles', 'print_emoji_styles' );
    remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
    remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
    remove_action( 'wp_print_styles', 'print_emoji_styles' );
    remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );
    remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
    remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );

    // filter to remove TinyMCE emojis
    add_filter( 'tiny_mce_plugins', 'autoptimize_extra_disable_emojis_tinymce' );

    // and remove dns-prefetch for emoji
    add_filter( 'wp_resource_hints', 'autoptimize_extra_emojis_remove_dns_prefetch', 10, 2 );
}

function autoptimize_extra_disable_emojis_tinymce( $plugins ) {
    if ( is_array( $plugins ) ) {
        return array_diff( $plugins, array( 'wpemoji' ) );
    } else {
        return array();
    }
}

function autoptimize_extra_emojis_remove_dns_prefetch( $urls, $relation_type ) {
    $_emoji_svg_url = apply_filters( 'emoji_svg_url', 'https://s.w.org/images/core/emoji/' );

    return autoptimize_extra_remove_dns_prefetch( $urls, $relation_type, $_emoji_svg_url );
}
```

The same code is available in the following plugin: https://wordpress.org/plugins/disable-emojis/

The request from the user was interesting however because from a optimization perspective users may want to remove or control script injected scripts.

We created a optimization innovation and added a new feature to the javascript proxy to delete script injected scripts enabling to specifically remove `/wp-includes/js/wp-emoji-release.min.js` while leaving the emoji functionality untouched.

Deleting WordPress emoji (specifically removing the javascript) is possible using the following entry in the Proxy Capture List:

```json
{"match":"wp-emoji-release.min.js", "delete": true}
```

There is also a new option to rewrite the URL of a script injected script. You can use Regular Expression for matching.

```json
{"match":"/script([0-9]+)\\.js", "regex": true, "rewrite": "https://cdn.domain.com/script.js"}
```

This feature provides advanced control over script injected scripts using simple JSON. For advanced optimization of javascript heavy / complex websites, it is of high value to achieve a Google Lighthouse 100 score.

An other example is that one of our partners requested to automatically add `"rel="nofollower"` to links to pass the Google Lighthouse test.

Also in this case a professional optimization innovation was created: **Advanced HTML link optimization** that includes the ability to optimize javascript (AJAX) injected links from social media and review widgets (using a DomObserver), enabling to pass the Google Lighthouse score while it would otherwise require manual modification of (external) javascript source files.

Using this solution you can remove or add attributes to links, add or remove classes or apply a CDN with mask (to script injected links).

https://github.com/o10n-x/wordpress-html-optimization/releases/tag/0.0.21

![image](https://user-images.githubusercontent.com/8843669/40358922-3ddef0c6-5dc1-11e8-8957-f6570584d612.png)

![image](https://user-images.githubusercontent.com/8843669/40358863-0485a7b6-5dc1-11e8-9a33-81af6a1ac67b.png)

This is the reason that the WPO plugins would not normally provide a `Disable for AMP` option. It will support it with the best performing methods. We recently made additional options available to disable the plugin efficiently.

```php
\O10n\disable();

define('O10N_DISABLED', true);

add_filter('o10n_disabled', function() { 
	
	# disable optimization for AMP pages
	if (function_exists('is_amp_endpoint') && is_amp_endpoint()) { return true; } 

	return false;
});
```

Users who want to use the optimization technologies for AMP will be able to, while disabling can be easily done as well.

We will investigate your feedback in regards to not being able to disable the plugin from a WordPress hook.

**Comment by optimalisatie** [comment]
A solution that will certainly work is the following in `wp-config.php`. It is also the best performing solution.

```php
# disable optimization for AMP pages
if (strpos($_SERVER['REQUEST_URI'],'/amp/) === 0) {
	define('O10N_DISABLED', true);
}
```

**Comment by AlphaDE** [comment]
I'll try, thanks

**Comment by AlphaDE** [comment]
Ok, I found the reason why the plugin was not working... my fault, a deleted "end comment" line...

Anyway, that works, thx for your help.

but... is there any chance to switch only certain functions off.

The security and the webfont plugin should continue to work.

**Comment by optimalisatie** [comment]
The latest update provides new options to disable the plugin and individual optimization modules.

### Disable optimization (global)

```php
// disable optimization
\O10n\disable();

# disable by constant
define('O10N_DISABLED', true);

# disable optimization for AMP pages in wp-config.php
if (strpos($_SERVER["REQUEST_URI"],'/amp/') === 0) {
	define('O10N_DISABLED', true);
}

# disable by WordPress filter
add_filter('o10n_disabled', function() { 
	
	# disable optimization for AMP pages
	if (function_exists('is_amp_endpoint') && is_amp_endpoint()) { return true; } 

	return false;
});
```

### Disable individual optimization modules (new)

```php
// disable webfont optimization
\O10n\disable(true, 'fonts');

// disable CSS and Javascript optimization
\O10n\disable(true, array('css', 'js'));

# disable by constant
define('O10N_DISABLED_CSS', true);
define('O10N_DISABLED_PWA', true);
define('O10N_DISABLED_SECURITY', true);

# disable Javascript optimization and file cache for AMP pages (wp-config.php)
if (strpos($_SERVER["REQUEST_URI"],'/amp/') === 0) {
	define('O10N_DISABLED_JS', true);
	define('O10N_DISABLED_FILECACHE', true);
}

# disable CSS optimization by WordPress filter
add_filter('o10n_disabled_css', function() { 
	
	# disable optimization for AMP pages
	if (function_exists('is_amp_endpoint') && is_amp_endpoint()) { return true; } 

	return false;
});
```

**Comment by AlphaDE** [comment]
Wow... that was fast. Thx very much.

**Comment by AlphaDE** [comment]
Some things...

First, the config.php if clause you posted needs a slight modification to work:

`if (strpos($_SERVER["REQUEST_URI"],'/amp/') !== 0) {`

Seconds, despite having installed the latest set of plugins, O10N_DISABLED_JS does not show an effect. O10N_DISABLE in config.php though does work.

**Comment by optimalisatie** [comment]
`!== false` will match any position in the URL, which could be a unrelated sub-category (e.g. `/docs/amp/`).

It may be best to exactly match the path position. `=== 0` matches the start position in the string. If you use a directory prefix before `/amp/` it may be best to use it as a match string, e.g.:

```php
if (strpos($_SERVER["REQUEST_URI"],'/path-to/amp/') === 0) {
```

**Comment by AlphaDE** [comment]
Ok.... the theme uses /amp/ or /?amp at the end, so I changed it to 

if ((strpos($_SERVER["REQUEST_URI"],'/amp/') === strlen($_SERVER["REQUEST_URI"])-5) || (strpos($_SERVER["REQUEST_URI"],'/?amp') === strlen($_SERVER["REQUEST_URI"])-5)) {

**Comment by AlphaDE** [comment]
John, an idea...

you have already filters to exclude single scripts from processing or even cut them out.

Would it be possible to access the request url and check the url against a search-string? That way, this amp matter could be done.
Moreover, I have some plugins (like PIE Register) injecting their scripts in each and every page although they are used on only one subpage (registration page). With such a function, I could remove these scripts just wasting space from pages where they're not required...

**Comment by optimalisatie** [comment]
I would suggest the following:

```php
# disable optimization for AMP
if (in_array(substr($_SERVER["REQUEST_URI"],-5),array('/?amp','/amp/'))) {
	define('O10N_DISABLED_FONTS', true);
	define('O10N_DISABLED_HTTP2', true);
}
```

In regards to your suggestion. It would have been possible with our original advanced optimization plugin. It provided in conditional optimization configuration to be able to setup a unique optimization for AMP. It would even enable to optimize a website for individual visitors or for example iPhone 5 users.

This isn't easily possible with the currently available WordPress plugin. You could use WordPress filters however to change configuration on the fly, achieving the desired result for AMP pages.
